[tools]
"cargo:cargo-audit" = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-hack" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-msrv" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:cargo-watch" = "latest"
"cargo:cbindgen" = "latest"
"cargo:wasm-bindgen-cli" = "latest"
"cargo:wasm-pack" = "latest"
"go:github.com/google/addlicense" = "latest"
"ubi:https://github.com/WebAssembly/wabt/releases/tag/1.0.37" = "latest"

# Build tools
cargo-binstall = "latest"
fd = "latest"
go = "prefix:1.24"
golangci-lint = "latest"
jq = "latest"
just = "latest"
node = "lts"
pnpm = "latest"
python = "prefix:3.12"
rust = "prefix:1.87"
uv = "latest"

[env]
COREPACK_ENABLE_DOWNLOAD_PROMPT = "1"
LIBRARY_PATH = "$LIBRARY_PATH:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib:/opt/homebrew/opt/libiconv/lib"
MACOSX_DEPLOYMENT_TARGET = "11.0"
RUST_BACKTRACE = "1"
RUSTFLAGS = "-D warnings"

[settings]
experimental = true
