[package]
name = "chumsky-helpers"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
ariadne = "0.5.0"
chumsky = "1.0.0-alpha.8"
thiserror = "2.0"
time = "0.3"

[dev-dependencies]
proptest = "1.6"
test-case = "3.3.1"

[lib]
path = "src/lib.rs"
